name: "build"

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: build
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.3'
          channel: stable

      - name: install Dependencies
        run: flutter pub get

      - name: build apk
        run: flutter run 
